development:
  secret_key_base: c70e0d1da3ff46ef16ea0cba8a1f2ccb79a499ee04c37333cd038ea2e6cfbab82c55499a0b7c54acaf77bae89a39316e8ff954bf1aaa05af9a75879c302b4a83

  google:
    client_id: development
    client_secret: development
test:
  secret_key_base: b7bf7b0d8f59ced29ef123a8e81ba35d0e794ada4582c21f438977319b67416c10b8609d8b65747fab50d9a0d9063fc69bb566b3f5f07a4dbe55845794c74e79
  google:
    client_id: test
    client_secret: test
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google:
    client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
    client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
  mashape:
    key: <%= ENV["MASHAPE_APP_KEY"] %>
